#For the provider URL: Use https://token.actions.githubusercontent.com
#For the "Audience": Use sts.amazonaws.com
name: Sync Site Files
on:
  push:
    paths:
      - site/**
env:
  AWS_REGION : "us-west-2"
  BUCKET_NAME: "dylan-resume-website"
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  Sync-S3-Bucket:
    name: 'Sync S3 Bucket'
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: site/

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::689736139044:role/github-resume-s3
          role-session-name: s3ResumeRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync S3 bucket
        run: aws s3 sync site s3://${{ env.BUCKET_NAME }}
