#For the provider URL: Use https://token.actions.githubusercontent.com
#For the "Audience": Use sts.amazonaws.com
name: Terraform Backend Bootstrap
on:
  push:
    paths:
      - "{{ env.DIR }}/**"
env:
  DIR : "infra/tf_backend"
  AWS_REGION : "us-west-2"
  GITHUB_ACTIONS_ROLE: "arn:aws:iam::689736139044:role/github-tf-backend"

  TF_VAR_aws_region: "us-west-2"
  TF_VAR_project_name: "dylan-resume-website"

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  terraform-backend-bootstrap:
    name: 'Terraform Backend Boostrap'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: "./${{ env.DIR }}"

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: "${{ env.DIR }}/"

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: {{ env.GITHUB_ACTIONS_ROLE }}
          role-session-name: s3ResumeRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false

        # On push to "main", deploy the Terraform infrastructure
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
